#!/bin/sh

# Default the release to bionic
RELEASE=buster

if [ $# -eq 0 ]; then
    echo "$0 <board> [Armbian build dir] [userpatches dir]" 1>&2
    exit 1
fi
BOARD=$1
if [ $# -eq 1 ]; then
    ADIR="${PWD}/armbian"
else
    ADIR=`realpath $2`
fi
if [ $# -lt 2 ]; then
    PDIR="${PWD}/userpatches"
else
    PDIR=`realpath $3`
fi
ARMBIAN_GIT="https://github.com/armbian/build.git"
if [ "${BOARD}" = "orangepizeroplus2-h3" ]; then
    EXTRA_OPTIONS="BRANCH=next"
elif [ "${BOARD}" = "nanopineo4" ]; then
    EXTRA_OPTIONS="BRANCH=legacy"
fi

# Ensure that the patches directory exists.
if [ ! -d ${PDIR} ]; then
    echo "Patch directory ${PDIR} does not exist."
    exit 2
fi

# Checkout the Armbian git repo or ensure the user specified
# a valid directory if the directory already exists.
if [ ! -d ${ADIR} ]; then
    echo "Cloning ${ARMBIAN_GIT} into ${ADIR}"
    git clone ${ARMBIAN_GIT} ${ADIR}
elif [ ! -f ${ADIR}/compile.sh ]; then
    echo "Missing compile.sh in the Armbian build directory." 1>&2
    exit 3
fi

# Change directory into the Armbian build directory
cd ${ADIR}

# Print the current git hash
echo "Current Armbian git hash: `git rev-parse HEAD`"

# Ensure the board name is valid.
if [ ! -f config/boards/${BOARD}.conf ]; then
    echo "Board ${BOARD} is not valid." 1>&2
    exit 4
fi

# Everything looks good. Fire up the build!
sudo ./compile.sh USERPATCHES_PATH=${PDIR} BOARD=${BOARD} ${EXTRA_OPTIONS} RELEASE=${RELEASE} BUILD_DESKTOP=no KERNEL_ONLY=NO KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BSPFREEZ=yes NO_APT_CACHER=yes | tee ${BOARD}.log
