#!/bin/bash

# Default the release to bionic
RELEASE=buster

if [ $# -eq 0 ]; then
    echo "$0 <board>" 1>&2
    exit 1
fi
BOARD=$1
ADIR="${PWD}/armbian"
PDIR="${PWD}/userpatches"
BRANCH=current

# Ensure that the patches directory exists.
if [ ! -d ${PDIR} ]; then
    echo "Patch directory ${PDIR} does not exist."
    exit 2
fi

# Ensure that the armbian submodule exists
if [ ! -d ${ADIR} ]; then
    echo "Updating armbian submodule"
    git submodule update --init
elif [ ! -f ${ADIR}/compile.sh ]; then
    echo "Missing compile.sh in the Armbian build directory: ${ADIR}/compile.sh" 1>&2
    exit 3
fi

# Change directory into the Armbian build directory
cd ${ADIR}

# Print the current git hash
echo "Current Armbian git hash: `git rev-parse HEAD`" | tee ${BOARD}.log

# Ensure the board name is valid.
if [ ! -f config/boards/${BOARD}.conf ]; then
    echo "Board ${BOARD} is not valid." 1>&2
    exit 4
fi

# Everything looks good. Fire up the build!
sudo ./compile.sh USERPATCHES_PATH=${PDIR} BOARD=${BOARD} BRANCH=${BRANCH} ${EXTRA_OPTIONS} RELEASE=${RELEASE} BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BSPFREEZ=yes NO_APT_CACHER=yes COMPRESS_OUTPUTIMAGE=7z SEVENZIP=yes |& tee -a ${BOARD}.log
