name: build-all

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: update-submodules
      run: git submodule update --init
    - name: build-nanopiduo2
      run: sudo scripts/build_image nanopiduo2
    - name: build-nanopineo4
      run: sudo scripts/build_image nanopineo4
    - name: build-nanopim4v2
      run: sudo scripts/build_image nanopineo4
    - name: build-nanopineoplus2
      run: sudo scripts/build_image nanopineoplus2
    - name: clean
      run: sudo rm -f armbian/output/images/*.img
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: images
        path: armbian/output/images
