name: build-nanopiduo2

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: clone-armbian
      run: git clone https://github.com/armbian/build.git ArmbianBuild
    - name: install-docker
      run: |
        sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 0EBFCD88 
        echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/docker.list
        sudo apt update
        sudo apt install docker-ce
    - name: build-image
      run: |
        cd ArmbianBuild
        sudo docker build -t lib .
        sudo docker run -i -P --privileged lib /root/compile.sh USERPATCHES_PATH=../userpatches BOARD=nanopiduo2 RELEASE=bionic BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BSPFREEZ=yes COMPRESS_OUTPUTIMAGE=gz
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nanopiduo2
        path: ArmbianBuild/output/images
