name: build-nanopiduo2

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-cacher-ng
    - name: build-image
      run: sudo scripts/build_image ArmbianBuild userpatches nanopiduo2
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nanopiduo2
        path: ArmbianBuild/output/images
