  
name: build-nanopineo4

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: build-image
      run: sudo scripts/build_image nanopineo4
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nanopineo4
        path: armbian/output/images
