name: build-nanopifire3

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: build-image
      run: sudo scripts/build_image nanopifire3
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nanopifire3
        path: armbian/output/images
