name: build-orangepizeroplus2-h3

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: build-image
      run: sudo scripts/build_image orangepizeroplus2-h3
    - name: upload-artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: orangepizeroplus2-h3
        path: armbian/output/images
